language: node_js
node_js:
  - "10"
  - "12"
deploy:
  skip_cleanup: true
  provider: npm
  on:
    tags: true
    branch: master
  email: open-source-ops@aexp.com
  api_key:
    secure: uVec0vOedRtsCiXad6bKcu8X/Qe02bVCb3EdTktsy1SNDCE9C5HK5coQTwX9yL02PEag5tKyev34lOontUlVPN4wlWf8GYqlgRFPKv0+fGv4MMjz3V8vFyq3TZxgc36DcMh5vzclTVtvDh+/KOHIedoT7TrnrpUDKQkQvzmNJmhKQH1PnHtKlDQbtXfc4YEhK9MkKS0ilAbhSCWUaU9wakmpyfIUd/+IktFFGYIJYpjLHBMXKJqMGc12cMkkPIeV0nM3f7Ijeo2GvkFXcwBq8VvE9h/5UXbc3Q39YAfEK8P3iBWvuVYEsWiPIMDutt+CMm04h56RyiDcus9AWEQsUCZ+zIulxbI67T4ZisBCxvsM5ake6NeF4ZhSeXbzuNhFjFXUN7Gh6GIpmho9eeIr3/MZW8GNoUzLT0V6c67EsYOb+xMsqPx+N6WQvQxXVahvLcU8F8lsVKUrhje6e7bFZO/PxOuZI8YagmulaDxQGEAGs3AfldYUkkbqibI9bJ+YB7t3xmi11OHHb0Q4I7grPbJD5gzS1/7YmnNYfJirF6icq2LGwpT259X771zEcxsYpTWHkb9dE8DqTnvmEr2PjJ3FcNXv6IFbrRxnzpiI59Xr5CjV/QUeMJle85rUyAUx0Nl1gE2+PXsivq8wBkGURe6hPUOjtxJ4KFIfE7nyaUU=
after_failure:
  - cat log.failure.txt
