language: node_js
node_js:
  - "10"
  - "12"
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email: open-source-ops@aexp.com
  api_key:
    secure: PzrM2jATvORO7sqIOkELQTqLFFAavtkcUs0owKNNe5rN4RhWY3AGGhWo2JC/hNrsTKZ/RY1xJtdz9vVNHLAMFl/y3AQHvMFiHlNqFPC/vq4s0/r7Kh3igAn3jEX0hYc74FYf+KzZQQacnYLgk2zGqDJ5wMuezRH/MNVrELhrN12Z2X4w86gh1oeotnxtxoIAnnqW2I/Hxv0SoFg2nlCuuHIj1/m8AEXLG7gdX7A6+kSLOOzXVTSSWAmEs+xQl7jZ6Y9K/GZhTFwoqhm0tpngl+M0w1fnTpxJ2EuSB05YEnvk0MgXemR+wCaTxWIxNTG8Jc1IrOeQhpMKbCJV/iDJttHLkpgfnIXYjiD23UMCVd4NXsFa2vwbuG3ULzx6zlPsto2ZEQbD6FVW/r67o6v96B3sOTLFl1BdACwQYmLHfBqyVgseawwdoNx23Erfx4pbLKM6joajlif8zpi2OOrA91HXj/vCPFxuBa1/2L60LMiD5QbvNakMqj9jBK7mY1LMQKQyagWdZgdzn7w5O8r7o0mCMQ8/doW1J2/LzpA8AWrMB9vjhBziIiLxgrIa3SebclgN1xKeEn3od88eUV6jLI2QUng19j9VKDEGKmrYCvSucEBZaKkHeRMBaoYAH1MHn8usVVt53sM9I4wObQi7pSpi0DytU50PpFO8sMUqxZY=
